# MÓDULO 3

# Aula 5 - Pacotes e NumPy

## 1.1 Carregando módulos ``import``


In [1]:
import math

Testando algumas funções

In [ ]:
math.pi

3.141592653589793

In [ ]:
math.cos(math.pi)

-1.0

Agora usando o Numpy, que é uma biblioteca padrão que já vem instalada no Python

In [2]:
import numpy as np

Explorando:

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.cos(np.pi)

np.float64(-1.0)

Outra forma de fazer o import é importando apenas as funções de interesse:

In [ ]:
from math import cos, pi

Explorando:

In [ ]:
cos(pi)

-1.0

Diferentemente do que fizemos acima, temos outra forma de importar, sem precisar dar apelido/alias à biblioteca, que é fazendo o seguinte:

In [ ]:
import numpy

In [ ]:
numpy.pi

3.141592653589793

Temos outra forma de importar, sem precisar dar apelido/alias à biblioteca e sem usar o método acima. Essa forma, porém, é pouco recomendada:

In [ ]:
from math import * # o asterisco importa todas as funções ao mesmo tempo

In [ ]:
sin(pi) ** 2 + cos(pi) ** 2

1.0

Quando usamos o ``import *`` ele substitui todas as funções padrões do python pelas funções do módulo carregado, o que pode gerar um comportamento não esperado. Esse último comando ``from numpy import *`` substitui a função ``sum`` do Pythons pela função ``numpy.sum`` (é como se uma função ficasse sobreescrita sobre a outra, de modo que funções/palavra reservadas do Python ou de quaisquer outras bibliotecas que estiverem sendo usadas sejam sobrescritas, gerando confusão) e existe diferenças entre elas. Por isso o ``import *`` deve ser evitado.

## 1.2 Bibliotecas padrão do Python

Documentação das bibliotecas padrão do Python: https://docs.python.org/pt-br/3/library/.

## 1.3 Instalando e importando módulos de terceiros

Os módulos que não são padrão do Python podem ser usados da mesma forma que os módulos padrão, mas antes disso devem ser instalados na nossa máquina.

Para isso, podemos utilizar o seguinte comando no CMD:
```
$ pip install nome_do_pacote
```
``pip`` é um comando que automaticamente baixa e instala os pacotes listados no PyPI (*Python Package Index*), que contém um repositório de módulos/funções.  

Após a instalação do módulo, a utilização dentro do jupyter notebook é igual ao das bibliotecas padrão usando o ``import``

Para mais informações sobre o PyPI, acesse o site: http://pypi.python.org/.

Outra opção é usar o site https://realpython.com, em que é possível selecionar a opção traduzir para o português; há várias dicas.

## 2.0 NumPy

Exemplo e texto adaptado de: https://numpy.org/

NumPy é o pacote essencial para computação científica em Python. É uma biblioteca Python que fornece um objeto array multidimensional (vetores e matrizes) e uma variedade de rotinas para operações rápidas.

A principal parte do pacote NumPy é o objeto NDArray, que é um conjunto de dados n-dimensional de tipos iguais de dados. Possui um desempenho superior se comparado às sequencias padrão do Python (lista, tupla, etc), pois as operações são realizadas em códigos compilados. Outras diferenças são:

Os arrays NumPy são de tamanho fixo e as listas não.

Os elementos dos arrays NumPy devem ser todos do mesmo tipo e na lista podem ter tipos diferentes.

Os arrays NumPy facilitam operações matemáticas em uma grande quantidade de dados. Normalmente, essas operações são executadas de forma mais eficiente e com menos código do que é possível usando as sequências do Python.

**Exemplo simples**

**Usando listas:**

In [ ]:
lst_a = [1, 2, 3, 4, 5]
lst_b = [6, 7, 8, 9, 10]

In [ ]:
lst_c = []
for i in range(len(lst_a)):
    lst_c.append(lst_a[i]*lst_b[i])
lst_c

[6, 14, 24, 36, 50]

**Usando NumPy:**

In [ ]:
array_a = np.array(lst_a)
array_b = np.array(lst_b)

In [ ]:
array_c = array_a * array_b

___

# Aula 6 - NDArrays (*N-dimensional array*)

## 1.0 Criando NDarrays

### 1.1 A partir de listas do Python ``np.array``


In [ ]:
np.array([5, 2, 3, 4, 1])

array([5, 2, 3, 4, 1])

In [ ]:
# só aceita um tipo de dado, se houver diferentes tipos, é transformado em apenas 1.
np.array([5, 2, 3, 4, 1.0])
# np.array([5, 2, 3, 4, '1'])


array([5., 2., 3., 4., 1.])

In [ ]:
#podemos explicitar o tipo de dado na construção.
np.array([5, 2, 3, 4, 1], dtype='float32')

array([5., 2., 3., 4., 1.], dtype=float32)

### 1.2 A partir de rotinas do NumPy ``np.zeros`` ``np.ones`` ``np.arrange`` ``np.random.randint``

Nas aulas anteriores, para criarmos grandes listas do Python (todos os números pares até o 200), usamos as estruturas de repetição ``while`` e ``for``.

Para criar grandes arrays podemos usar rotinas do NumPy.

In [ ]:
#criando um vetor de zeros
vetor_zeros = np.zeros(5)
vetor_zeros

array([0., 0., 0., 0., 0.])

In [ ]:
#criando uma matriz de zeros
matriz_zeros = np.zeros((2, 5))
matriz_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#criando array dos numeros pares
pares = np.arange(2, 22, 2)# (inicio, fim, paço)
pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.random.rand(3,2) # monta uma matriz 3x2 com valores randomicos

array([[0.20872918, 0.8603778 ],
       [0.66820434, 0.45289926],
       [0.44362338, 0.11412004]])

In [ ]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(5, size=(3, 3))

array([[2, 4, 3],
       [2, 4, 4],
       [1, 0, 4]])

More advanced type specification is possible, such as specifying big or little endian numbers; for more information, refer to the [NumPy documentation](http://numpy.org/).
NumPy also supports compound data types, which will be covered in [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb).

## 2.0 Aritmética com NDarrays

In [ ]:
array_2 = np.array([2, 2, 2, 2, 2])
array_10 = np.array([10, 10, 10, 10, 10])

In [ ]:
array_2+2

array([4, 4, 4, 4, 4])

In [ ]:
array_2+array_10

array([12, 12, 12, 12, 12])

In [ ]:
array_2*array_10

array([20, 20, 20, 20, 20])

In [ ]:
array_10/array_2

array([5., 5., 5., 5., 5.])

In [ ]:
array_10**array_2

array([100, 100, 100, 100, 100])

Definindo um novo array:

In [ ]:
array_1a5 = np.array([1, 2, 3, 4, 5])

Vejamos as operações:

In [ ]:
array_1a5**array_2

array([ 1,  4,  9, 16, 25])

In [ ]:
array_1a5**2

array([ 1,  4,  9, 16, 25])

# Aula 7 - Indexação e Matrizes

## 1.0 Indexação básica, indexação booleana e fatiamento

In [ ]:
array_primos = np.array([2, 3, 5, 7, 11])
array_primos

array([ 2,  3,  5,  7, 11])

<img src="list-indexing.png">

https://github.com/jakevdp/WhirlwindTourOfPython/blob/master/fig/list-indexing.png

In [ ]:
#vamos praticar com alguns exemplos de indexação básica
array_primos

array([ 2,  3,  5,  7, 11])

Para acessar valores do array, fazemos assim:

In [ ]:
array_primos[3] # vai imprimir 7

np.int64(7)

Note que para acessar um elemento, como fizemos acima, uamos a indexação padrão: 0 para o primeiro elemento, 1 para o segundpo, etc.

Agora considere que vamos precisar fazer outro tipo de indexação.

Um tipo de indexação interessante é a **indexação booleana**.

In [ ]:
bool_lista = [True, False, True, True, False]
bool_lista

[True, False, True, True, False]

Apliacando a indexação, temos:

In [ ]:
# boolean list
array_primos[bool_lista]

array([2, 5, 7])

Também é possível fazer uma indexação às aversas, em que usamos o sentido contrário para acessar valores do array.

In [ ]:
print(array_primos[-2]) # acesso ao penultimo elemento do array
print(array_primos[-1]) # acesso ao ultimo elemento do array

7
11


O **fatiamento** consiste em uma forma de acessar apenas alguns elementos do array por meio através de fatias/subconjuntos/intervalos. Exemplo:

In [ ]:
#fatiamento
array_primos[2:4] # nao consideram o elemento da ultima posição (colocamos do 2 ao 4, que são 5 e 7, não incluindo o 11)

array([5, 7])

In [ ]:
array_primos[2:-1]

array([5, 7])

In [ ]:
array_primos[-3:-1]

array([5, 7])

## 2.0 Matrizes

O array também é utilizado para criar matrizes.

No exemplo abaixo, vamos escrever uma matriz que relacione a dívida financeira com a renda familiar.

|  Dívida financeira | Renda familiar |
|:----:|:---|
| 1000 | 6000 |
| 2500 | 5500 |
| 3000 | 7000 |

In [ ]:
matriz_3x2 = np.array([[1000,6000], [2500, 5500], [3000, 7000]])
matriz_3x2

array([[1000, 6000],
       [2500, 5500],
       [3000, 7000]])

### Como acessar valores de uma matriz

Uma forma de exibir todas as linhas e todas as colunas é escrevendo matriz_3x2 e rodando. Mas usando o comando abaixo também funciona: com os dois pontos (:) ele exibe todas as linhas e todas as colunas.

In [ ]:
matriz_3x2[:,:]

array([[1000, 6000],
       [2500, 5500],
       [3000, 7000]])

Se quisermos só as últimas 2 linhas, basta escrever 1: no primeiro argumento e manter o : no segundo argumento:

In [ ]:
matriz_3x2[1:, :]

array([[2500, 5500],
       [3000, 7000]])

Se quisermos só a últimas  linha, basta escrever 2: no primeiro argumento e manter o : no segundo argumento:

In [ ]:
matriz_3x2[2:, :]

array([[3000, 7000]])

Podemos, assim, acessar valores diversos de uma matriz. Seguem mais alguns exemplos:

In [ ]:
matriz_3x2[:, 1:]

array([[6000],
       [5500],
       [7000]])

Veja que, dessa forma, a gente manteve todas as linhas e ficamos só com a segunda coluna. Caso queiramos a coluna 1, em vez da 2, com todas as linhas, a gente **não usa o :**, como abaixo:

In [ ]:
matriz_3x2[:, 0]

array([1000, 2500, 3000])

Para acessar só a coluna 2:

In [ ]:
matriz_3x2[:, 1]

array([6000, 5500, 7000])

In [ ]:
matriz_3x2[:, 1:]

array([[6000],
       [5500],
       [7000]])

In [ ]:
matriz_3x2[1:, 1:]

array([[5500],
       [7000]])

In [ ]:
matriz_3x2[2:, 1:]

array([[7000]])

### Operações com arrays - exemplo para avaliar a saúde financeira de um grupo familiar


Considere que a gente queira saber quanto a dívida representa da renda familiar de cada família.

Para fazer essa operação, seguimos com a forma: vamos dividir a Renda familiar pelo valor da dívida. Quanto maior o resultado, melhor a saúde financeira da família, reduzindo a possibilidade de ela vir a se endividar mais ainda.

Esse exemplo é aplicável a modelos de riscos, modelos de inadimplência, modelo de risco de crédito, etc.

In [ ]:
# coluna de dados da renda
matriz_3x2[:, 1]

array([6000, 5500, 7000])

In [ ]:
#coluna de dados da dívida

matriz_3x2[:, 0]

array([1000, 2500, 3000])

In [ ]:
matriz_3x2[:,1]/matriz_3x2[:,0]

array([6.        , 2.2       , 2.33333333])

A família 6 parece a mais saudável.

___

# Aula 8 - Construindo e usando funções

## 1.0 Algumas funções nativas

Já utilizamos diversas funções nativas como:

- A função **print()** que é útil para retornar resultados no output do *jupyter notebook*.
- A função **len()** que retorna o tamanho de uma string ou lista.
- A função **type()** que retorna o tipo de dado.
- As funções **int(), float(), bool() e str()** retornam o argumento inserido na forma de um int, float, bool ou str, respectivamente.

### 1.1 A documentação do Python contém uma [lista](https://docs.python.org/pt-br/3/library/functions.html) de todas as funções nativas (built-in-functions).

## 2.0 Escrevendo uma função ``def``

Uma boa maneira de organizar, deixar mais legível e mais reutilizável os códigos em python é tornando-os uma função. Vamos cobrir esse tema agora e mostrar 2 maneiras de construir uma função.

### Fórmula IMC

$$IMC = \frac{PESO}{ALTURA*ALTURA}$$
Sendo peso em kg e a altura em metro


In [ ]:
# meu imc; só fiz o inverso do inverso para testar o atalho: para colocar uma coisa entre parenteses, basta selecionar o trecho e abrir parênteses

1/((1.60*1.60)/90)

35.15624999999999

In [ ]:
90/(1.6*1.6)

35.15624999999999

In [ ]:
90/(1.90*1.90)

24.930747922437675

In [ ]:
def calcula_IMC_lucas():
    return 80/(1.90*1.90)

In [ ]:
calcula_IMC_lucas()

22.1606648199446

Vou testar uma função para calcular meu pesinho:

In [ ]:
def calcula_imc_da_polizinha():
  return print(f'Esse é o IMC da Polizinha: {60/(1.6*1.6)}')

Chamando agora:

In [ ]:
calcula_imc_da_polizinha()

Esse é o IMC da Polizinha: 23.437499999999996


Agora definindo a função com variáveis, permitindo que a gente consiga passar só os valores de interesse.

In [ ]:
def calcula_IMC(peso,altura):
    imc = peso/(altura*altura)
    return imc

In [ ]:
calcula_IMC(90,1.90)

24.930747922437675

- Muito abaixo do peso: 16 a 16,9 kg/m2
- Abaixo do peso: 17 a 18,4 kg/m2
- Peso normal: 18,5 a 24,9 kg/m2
- Acima do peso: 25 a 29,9 kg/m2

Agora vamos adicionar mais complexidade, retornando a informação de se a pessoa está com o peso ideal:

In [ ]:
def calcula_IMC(peso,altura):
    imc = peso/(altura*altura)
    if imc < 17:
        print('Muito abaixo do peso')
    elif imc < 18.5:
        print('Abaixo do peso')
    elif imc < 25:
        print('Peso normal')
    else:
        print('Acima do peso')
    return imc

Vejamos as 3 maneiras de exibir esse resultado:

In [ ]:
resultado_imc = calcula_IMC(90, 1.90)

Peso normal


In [ ]:
resultado_imc

24.930747922437675

In [ ]:
calcula_IMC(90, 1.60)

Acima do peso


35.15624999999999

In [ ]:
imc_pessoa_2 = calcula_IMC(80, 1.60)
imc_pessoa_1 = calcula_IMC(90, 1.90)
imc_pessoa_3 = calcula_IMC(60, 1.60)

Acima do peso
Peso normal
Peso normal


In [ ]:
print(imc_pessoa_1)
print(imc_pessoa_2)
print(imc_pessoa_3)

24.930747922437675
31.249999999999993
23.437499999999996


Qusanndo queremos deixar alguns parâmetros padrão, sem precisar ficar passando seus valores, podemos fixar um default, como abaixo:

In [ ]:
def calcula_IMC_com_default(peso=90, altura=1.90):
    imc = peso / (altura * altura)
    if imc < 17:
        print('Muito abaixo do peso')
    elif imc < 18.5:
        print('Abaixo do peso')
    elif imc < 25:
        print('Peso normal')
    else:
        print('Acima do peso')
    return imc

In [ ]:
calcula_IMC_com_default()

Peso normal


24.930747922437675

## 3.0 Escrevendo uma função ``lambda``

In [ ]:
calcula_imc_lambda = lambda peso, altura: peso/(altura*altura)
calcula_imc_lambda(90, 1.90)

24.930747922437675

**Equivalente à:**

In [ ]:
def calcula_IMC_def(peso,altura):
    return peso/(altura*altura)
calcula_IMC_def(90, 1.90)

24.930747922437675

## 4.0 Métodos

Métodos são funções associadas à classe do objeto, e são chamadas como ```<nome_do_objeto>.<nome_do_método>```. Por exemplo, se você tem uma variável que contém um string chamada exemplo_texto, você pode chamar o método ```lower()``` da seguinte forma: ```exemplo_texto.lower()```


In [ ]:
exemplo_texto = "R. Saturnino de Brito, 74"
exemplo_texto.lower()

'r. saturnino de brito, 74'

### 4.1 Métodos de *str*

Sendo ```meu_string```uma variável tipo string, todos os métodos abaixo são usados na forma ```meu_string.método()```. Alguns deles requerem ou têm como opcional um parâmetro dentro dos parêntesis, como o método ```meu_string.count('abc')```, que conta o número de ocorrências do string 'abc' dentro da variável ```meu_string```.

Como os métodos e funções disponíveis são muitos, o aprendizado depende fortemente do contato e experiência com eles, então pratique sempre que tiver a oportunidade.


Observe que strings são dados **imutáveis**, isso significa que seu conteúdo não pode ser alterado sem construir uma variável completamente nova. Portanto, métodos de strings sempre retornam uma cópia da variável original alterada. Abaixo listamos alguns métodos de string que selecionamos:

- meu_string.**lower**(): retorna uma cópia de ```meu_string``` em letras minúsculas.
- meu_string.**upper**(): retorna uma cópia de ```meu_string``` em letras maiúsculas.
- meu_string.**capitalize**(): retorna uma cópia de ```meu_string``` com a primeira letra maiúscula.
- meu_string.**count**(substring): conta quantas vezes a sequencia ```substring``` aparece em ```meu_string```
- meu_string.**endswith**(sufixo): retorna um *boolean* conforme ```meu_string```inicia com a sequencia de ```sufixo```
- meu_string.**find**(): retorna a posição em que ```sub``` ocorre dentro de ```meu_string```. **Nota:** Se você quer verificar se ```sub``` ocorre dentro de ```meu_string```, utilize a construção ```sub in meu_string```.

**OBS:** Na [documentação do Python](https://docs.python.org/pt-br/3/library/stdtypes.html) você encontra todos os métodos de *str* nativos disponíveis. Além disso, haverão outros ainda que se mostrarão úteis e que serão carregados com pacotes específicos do Python.

In [ ]:
meu_string = "Não são pedras"
meu_string.upper()

'NÃO SÃO PEDRAS'

In [ ]:
meu_string = "Não são pedras"
meu_string.casefold()

'não são pedras'

In [ ]:
meu_string = "Não são pedras"
meu_string.count('o')

2

# ATIVIDADE 2

Você tem duas strings: ```nome_campo``` e ```nome_cadastro```, uma delas veio através de um campo preenchido pelo usuário, e a outra veio de uma tabela cadastral do sistema. Escreva uma função que compara as duas retornando ```True``` caso sejam iguais e ```False```caso sejam diferentes, sem considerar diferenças de maiúsculas e minúsculas utilizando um dos métodos vistos.

In [3]:
def compara_nome(nome_campo, nome_sistema):
    #pass
    # Minha ideia: Fazer um array com cada caracter de cada parâmetro e verificar 1 a 1 se são iguais
    # na hora que ao menos 1 caracter for diferente, ele deve dar o break e printar False
    # Antes disso, um primeiro passo é jogar tudo para maiúscula (ou minúscula), já que, pelo enunciado, não vamos considerar essas diferenças
    nome_campo.lower()
    nome_sistema.lower()

    if len(nome_campo) == len(nome_sistema):
        for i in range(len(nome_campo)):
            if nome_campo[i] != nome_sistema[i]:
                return False
                #break
        return True
    else:
        return False



In [4]:
nome_campo = "Maria Clara Alves Cândido Simião"

In [5]:
nome_sistema = "Maria Claua Alves Cândido Simião"

In [6]:
compara_nome(nome_campo, nome_sistema)

False

Tendo como input ```nome```, ```sobrenome``` e ```nome completo```, escreva duas funções que:
a) identifiquem se o nome e sobrenome estão contidos no nome completo
b) dado verdadeiro na anterior, retorne ```True``` se o nome completo está no formato de citação (sobrenome antes do nome) e ```False``` caso contrário.

In [ ]:
nome = "Ana"
sobrenome = "Castro"
nome_completo = "Ana Castroeb"